/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "code.eoitek.net/monitor/dc/k8s-crd/apis/agent.eoitek.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProfileConfigs implements ProfileConfigInterface
type FakeProfileConfigs struct {
	Fake *FakeAgentV1beta1
	ns   string
}

var profileconfigsResource = schema.GroupVersionResource{Group: "agent.eoitek.io", Version: "v1beta1", Resource: "profileconfigs"}

var profileconfigsKind = schema.GroupVersionKind{Group: "agent.eoitek.io", Version: "v1beta1", Kind: "ProfileConfig"}

// Get takes name of the profileConfig, and returns the corresponding profileConfig object, and an error if there is any.
func (c *FakeProfileConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ProfileConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(profileconfigsResource, c.ns, name), &v1beta1.ProfileConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProfileConfig), err
}

// List takes label and field selectors, and returns the list of ProfileConfigs that match those selectors.
func (c *FakeProfileConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ProfileConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(profileconfigsResource, profileconfigsKind, c.ns, opts), &v1beta1.ProfileConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ProfileConfigList{ListMeta: obj.(*v1beta1.ProfileConfigList).ListMeta}
	for _, item := range obj.(*v1beta1.ProfileConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested profileConfigs.
func (c *FakeProfileConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(profileconfigsResource, c.ns, opts))

}

// Create takes the representation of a profileConfig and creates it.  Returns the server's representation of the profileConfig, and an error, if there is any.
func (c *FakeProfileConfigs) Create(ctx context.Context, profileConfig *v1beta1.ProfileConfig, opts v1.CreateOptions) (result *v1beta1.ProfileConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(profileconfigsResource, c.ns, profileConfig), &v1beta1.ProfileConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProfileConfig), err
}

// Update takes the representation of a profileConfig and updates it. Returns the server's representation of the profileConfig, and an error, if there is any.
func (c *FakeProfileConfigs) Update(ctx context.Context, profileConfig *v1beta1.ProfileConfig, opts v1.UpdateOptions) (result *v1beta1.ProfileConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(profileconfigsResource, c.ns, profileConfig), &v1beta1.ProfileConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProfileConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProfileConfigs) UpdateStatus(ctx context.Context, profileConfig *v1beta1.ProfileConfig, opts v1.UpdateOptions) (*v1beta1.ProfileConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(profileconfigsResource, "status", c.ns, profileConfig), &v1beta1.ProfileConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProfileConfig), err
}

// Delete takes name of the profileConfig and deletes it. Returns an error if one occurs.
func (c *FakeProfileConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(profileconfigsResource, c.ns, name, opts), &v1beta1.ProfileConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProfileConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(profileconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ProfileConfigList{})
	return err
}

// Patch applies the patch and returns the patched profileConfig.
func (c *FakeProfileConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ProfileConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(profileconfigsResource, c.ns, name, pt, data, subresources...), &v1beta1.ProfileConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProfileConfig), err
}
