/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/eoidc2024/k8s-crd/datadog/apis/agent.eoitek.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrontabConfigs implements CrontabConfigInterface
type FakeCrontabConfigs struct {
	Fake *FakeAgentV1beta1
	ns   string
}

var crontabconfigsResource = schema.GroupVersionResource{Group: "agent.eoitek.io", Version: "v1beta1", Resource: "crontabconfigs"}

var crontabconfigsKind = schema.GroupVersionKind{Group: "agent.eoitek.io", Version: "v1beta1", Kind: "CrontabConfig"}

// Get takes name of the crontabConfig, and returns the corresponding crontabConfig object, and an error if there is any.
func (c *FakeCrontabConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.CrontabConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crontabconfigsResource, c.ns, name), &v1beta1.CrontabConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CrontabConfig), err
}

// List takes label and field selectors, and returns the list of CrontabConfigs that match those selectors.
func (c *FakeCrontabConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.CrontabConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crontabconfigsResource, crontabconfigsKind, c.ns, opts), &v1beta1.CrontabConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.CrontabConfigList{ListMeta: obj.(*v1beta1.CrontabConfigList).ListMeta}
	for _, item := range obj.(*v1beta1.CrontabConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crontabConfigs.
func (c *FakeCrontabConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crontabconfigsResource, c.ns, opts))

}

// Create takes the representation of a crontabConfig and creates it.  Returns the server's representation of the crontabConfig, and an error, if there is any.
func (c *FakeCrontabConfigs) Create(ctx context.Context, crontabConfig *v1beta1.CrontabConfig, opts v1.CreateOptions) (result *v1beta1.CrontabConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crontabconfigsResource, c.ns, crontabConfig), &v1beta1.CrontabConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CrontabConfig), err
}

// Update takes the representation of a crontabConfig and updates it. Returns the server's representation of the crontabConfig, and an error, if there is any.
func (c *FakeCrontabConfigs) Update(ctx context.Context, crontabConfig *v1beta1.CrontabConfig, opts v1.UpdateOptions) (result *v1beta1.CrontabConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crontabconfigsResource, c.ns, crontabConfig), &v1beta1.CrontabConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CrontabConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrontabConfigs) UpdateStatus(ctx context.Context, crontabConfig *v1beta1.CrontabConfig, opts v1.UpdateOptions) (*v1beta1.CrontabConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crontabconfigsResource, "status", c.ns, crontabConfig), &v1beta1.CrontabConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CrontabConfig), err
}

// Delete takes name of the crontabConfig and deletes it. Returns an error if one occurs.
func (c *FakeCrontabConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(crontabconfigsResource, c.ns, name, opts), &v1beta1.CrontabConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrontabConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crontabconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.CrontabConfigList{})
	return err
}

// Patch applies the patch and returns the patched crontabConfig.
func (c *FakeCrontabConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CrontabConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crontabconfigsResource, c.ns, name, pt, data, subresources...), &v1beta1.CrontabConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CrontabConfig), err
}
